function addActive(){
    const tab1 = document.getElementById('tab1')    
    const tab2 = document.getElementById('tab2')
    const tab1Mobile = document.getElementById('tab1Mobile')    
    const tab2Mobile = document.getElementById('tab2Mobile')   
    const pic1 = document.getElementById('layer3')  
    const pic2 = document.getElementById('layer4') 
    const sched1 = document.getElementById('finalText1')
    const sched2 = document.getElementById('finalText2')
    const sched1Mobile = document.getElementById('finalText1Mobile')
    const sched2Mobile = document.getElementById('finalText2Mobile')
    const pic1Mobile = document.getElementById('layer3Mobile')  
    const pic2Mobile = document.getElementById('layer4Mobile') 
    sched1.classList.toggle('active')  
    sched2.classList.toggle('active')   
    tab1.classList.toggle('active')  
    tab2.classList.toggle('active')  
    pic1.classList.toggle('active')  
    pic2.classList.toggle('active') 
    pic1Mobile.classList.toggle('active')  
    pic2Mobile.classList.toggle('active') 
    sched1Mobile.classList.toggle('active') 
    sched2Mobile.classList.toggle('active') 
    tab1Mobile.classList.toggle('active') 
    tab2Mobile.classList.toggle('active') 
}